1) asyncWrapper was implemented to get rid of repetitiveness of trycatch blocks and make code more readable.
2) 

const {customError} = require('./errors/custom-errors')

const getTask = asyncWrapper(async (req, res, next) => {  
  const { id: taskID } = req.params;  
  const task = await Task.findOne({ _id: taskID });  
  if (!task) {  
    ///////////////// your code here  
        return (next(customError(`Error: ${taskID} is not found`, 404)))
    /////////////////
  }  
  res.status(200).json({ task });  
});  